---
abstract: 'Convert between perl data structures and ASN.1 encoded packets'
author:
  - 'Graham Barr <gbarr@cpan.org>'
build_requires:
  Math::BigInt: 1.997
  Test::More: 0.90
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300015, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Convert-ASN1
no_index:
  directory:
    - lib/Convert/ASN1
    - t
    - examples
resources:
  bugtracker: https://github.com/gbarr/perl-Convert-ASN1/issues
  repository: git://github.com/gbarr/perl-Convert-ASN1.git
version: 0.26
